### ISSUE TITLE
OnChainTx event may not be raised at channel creation in TestNet

### ISSUE THREAD

**Issue by hernandp** [aeternity/aepp-sdk-js#766] opened 2019-11-06 19:23 UTC
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

Channel creation on-chain transaction can be tracked by listening for the `onChain` event as documented.   However, sometimes there is no data available -no event is received-  even when the channel-creation-tx is effectively posted on chain, verified as soon as the channel creation succeeds.

This has been verified several times in Test nodes, 5.X family.
As far as I know, this buggy behavior is not seen when connected to Mainnet nodes.

* **What is the expected behavior?**

As documentation states, onChainTx should be received as soon as the transaction is posted on-chain.

Tracking 
* **Please tell us about your environment:**
  
  - Node Version: v5.0.2
  - SDK Version: v6.0.0
  - Environment: browser

**Comment by mpowaga** [comment] 2019-11-13 11:53
@hernandp I can't replicate this issue. Tested with two setups:

- locally with node `v5.0.0-rc.5` and `@aeternity/aepp-sdk@6.0.0`
- testnet `https://sdk-testnet.aepps.com` with node `v5.1.0` and `@aeternity/aepp-sdk@6.0.0`

Can you share a code which reproduces this error? This could also be a problem with the node.

**Comment by hernandp** [comment] 2019-11-13 15:04
Seems to appear at particular conditions.  Let me do a bit of research and I will ping you back.

**Comment by noandrea** [comment] 2019-11-19 10:55
@hernandp do you have any updates on this one?

**Comment by noandrea** [comment] 2019-12-17 16:14
@hernandp I'm closing this one since there are no updates, please reopen if needed

**Closed by noandrea** 2019-12-17 16:14 UTC
Labels: triage
