### ISSUE TITLE
Rename "Ae" to something better when used via script tag

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1114] opened 2021-02-22 11:09 UTC
Proposing variants:
- AeppSdk (isn't `aepp` term is outdated?)
- AeSdk
- AeternitySdk
- AeternityAeppSdk (according to package name, but seems too long)

**Comment by subhod-i** [comment] 2021-11-03 07:39
Seems like a duplicate of #1300.

**Comment by davidyuk** [comment] 2021-12-24 14:34
They overlap a bit. Actually, this ticket depends on the mentioned

**Comment by davidyuk** [comment] 2022-08-02 12:36
"AeSdk" doesn't fits here because it would contain `AeSdk`, I would rename `Ae` to `Aeternity` to avoid possible conflicts with other packages/variables. It will look this way:
```js
<script type="text/javascript">
const { Node, AeSdk, MemoryAccount } = Aeternity;
...
```

**Closed** 2022-08-09 14:41 UTC
Labels: enhancement, breaking changes
