### ISSUE TITLE
`contractCompile` using swagger client produces error (`v8.2.0`)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1225] opened 2021-06-17 21:57 UTC
again I am playing around with examples in the docs and recently updated to the release `v8.2.0`

it seems like there was some change that results in `contractCompile` producing sth. which leads to a bad request when calling the http compiler. when using `v8.1.0` the same code works as expected

## Function
```js
await client.contractCompile(CONTRACT_CODE)
```

## Error
```bash
Error: Bad Request
    at http (/home/marc0olo/.nvm/versions/node/v16.3.0/lib/node_modules/@aeternity/aepp-sdk/node_modules/swagger-client/lib/http.js:106:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 400,
  statusCode: 400,
  response: {
    ok: false,
    url: 'https://compiler.aepps.com:443/compile',
    status: 400,
    statusText: 'Bad Request',
    headers: {
      connection: 'close',
      'content-length': '54',
      'content-type': 'application/json',
      date: [ 'Thu', '17 Jun 2021 21:52:00 GMT' ],
      server: 'Cowboy'
    },
    text: '{"info":"","parameter":"","reason":"validation_error"}',
    data: '{"info":"","parameter":"","reason":"validation_error"}',
    body: { info: '', parameter: '', reason: 'validation_error' },
    obj: { info: '', parameter: '', reason: 'validation_error' }
  }
}
```

**Comment by sunbx** [comment] 2021-06-18 02:50
Yes, so do I. I use 8.1.0 version and can compile the contract normally. If I change to 8.2.0, it will cause an error
![image](https://user-images.githubusercontent.com/8652427/122499063-ca834c80-d022-11eb-941d-25bd13b902b3.png)
![IMG_584E3D73957C-1](https://user-images.githubusercontent.com/8652427/122499112-e2f36700-d022-11eb-9466-700684b5fe10.jpeg)

**Comment by mradkov** [comment] 2021-06-18 07:30
Do you guys mind sharing some code?

As all of the tests are passing for hits, are you sure it's not related to the contract code you are trying to compile?

`v8.2.0` uses compiler `6.0.0`.

**Comment by marc0olo** [comment] 2021-06-18 08:07
@mradkov should occur when running the node example in the repo:
- https://github.com/aeternity/aepp-sdk-js/blob/master/examples/node/contract.js

I was updating it and faced the issue with 8.2.0 for compilation

**Comment by marc0olo** [comment] 2021-06-18 08:29
here the codepen example. for 8.1.0 I cannot show it because the browser script was broken there:
- https://codepen.io/marc0olo/pen/ExWMvbP

**Comment by davidyuk** [comment] 2021-06-18 11:58
Recently I have dropped the support of node@5 the same as a workaround that actually needed for our compiler deployment: https://github.com/aeternity/aepp-sdk-js/pull/1218/commits/f5e2fdb42cc115a11c6be6e3dfd5cd1acfd6d3cc#diff-95fa4998e94b57e3debb9d34aaf93a764251db8e76e5e067a7c1315aa025a3abL59

The problem is that compiler's [swagger file](https://compiler.aepps.com/api) contains `"schemes":["http"]`. This makes `swagger-client` to request compiler by HTTP that is getting redirected to HTTPS because of compiler deployment. There are some issues making that for POST requests: https://stackoverflow.com/questions/31620987/redirecting-http-post-requests-to-https-post-requests

I'm proposing to revert a workaround for aeternity's compiler in #1226 until it would be resolved in https://github.com/aeternity/aesophia_http/issues/70 and https://github.com/orgs/aeternity/projects/4#card-63386022

**Closed** 2021-06-21 11:17 UTC
Labels: bug
