### ISSUE TITLE
Record fields are returned but not decoded

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1156] opened 2021-04-26 13:20 UTC
Hey everyone, I'm seeing a strange SDK behaviour for

```
    record user = {
        name: string,
        surname: string
      }

    entrypoint test(input: user) : string =
        input.surname
```

where calling with `{"name": "Alfred", "surname": "Mustermann"}`

gives me contradicting data: 
```
returnValue : cb_JXVuZGVmaW5lZENt6DE=
decodedResult : undefined
```

Similar for the same call data but using 
```
    entrypoint test(input: user) : user =
        input
```

it detects the fields, but doesn't get the data right:
```
returnValue : cb_KyV1bmRlZmluZWQldW5kZWZpbmVkW7amyg==
decodedResult :
name : undefined
surname : undefined
```

**Comment by davidyuk** [comment] 2021-04-26 16:37
I can't reproduce this on the develop branch:
```js
const { Universal: Sdk, Node, MemoryAccount } = require('../../dist/aepp-sdk')

const CONTRACT_CODE = `
contract Test =
  record user = { name: string, surname: string }
  entrypoint test(input: user) : string =
    input.surname
`
const CONTRACT_CODE_2 = `
contract Test =
  record user = { name: string, surname: string }
  entrypoint test(input: user) : user =
    input
`
const ACCOUNT_KEYPAIR = {
  publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
  secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b'
}
const NODE_URL = 'https://testnet.aeternity.io'
const account = MemoryAccount({ keypair: ACCOUNT_KEYPAIR });

(async () => {
  const node = await Node({ url: NODE_URL })

  const sdk = await Sdk({
    nodes: [{ name: 'testnet', instance: node }],
    compilerUrl: 'https://compiler.aepps.com',
    accounts: [account]
  })

  let contract = await sdk.getContractInstance(CONTRACT_CODE)
  await contract.deploy()
  let result = await contract.methods.test({"name":"Alfred","surname":"Mustermann"})
  console.log('decodedResult', result.decodedResult)

  contract = await sdk.getContractInstance(CONTRACT_CODE_2)
  await contract.deploy();
  result = await contract.methods.test({"name":"Alfred","surname":"Mustermann"})
  console.log('decodedResult2', result.decodedResult)
})()
```
```bash
$ node contract.js
decodedResult Mustermann
decodedResult2 { name: 'Alfred', surname: 'Mustermann' }
```

**Comment by nikita-fuchs** [comment] 2021-04-26 16:59
ok 🤷‍♂️ close with next release ;)

**Comment by subhod-i** [comment] 2021-11-02 11:19
@nikita-fuchs Can we close this issue or does the issue still persist?

**Comment by marc0olo** [comment] 2021-11-02 12:38
this is already addressed for a long time as @davidyuk mentioned. closing this now ;-)

**Closed by marc0olo** 2021-11-02 12:38 UTC
Labels: bug
