### ISSUE TITLE
Missing dependency 'stream' in subpackages

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#530] opened 2019-07-11 16:33 UTC
came across this oddity in angular:

```
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/ethereumbook/Documents/DAPPS/Angular/Angular8/demo-form-sku/node_modules/cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in '/Users/ethereumbook/Documents/DAPPS/Angular/Angular8/demo-form-sku/node_modules/hash-base'
```

anyways, installing `stream` manually makes it work.

**Comment by nikita-fuchs** [comment] 2019-07-11 19:53
although, I'm not really sure anymore. Getting an error in `cipher-base`: It `require`s

```
var Transform = require('stream').Transform
```
but the npm package `stream` doesn't export Transform. Seems more like node's built-in `Stream`api is concerned here: https://nodejs.org/api/stream.html

That's why Angular throws
```
ERROR TypeError: Cannot read property 'call' of undefined
    at Hash.CipherBase (index.js:7)
```, because 
```
function CipherBase (hashMode) {
  Transform.call(this)
...
```
cannot be called.

It was foolish of me to ```import { Crypto } from '@aeternity/aepp-sdk/es' ``` in browser as it relies on the non-browser-suitable APIs..  but isn't there a way ? Seems like https://www.npmjs.com/package/crypto-browserify doesn't support our curve, or does it?

**Comment by shekhar-shubhendu** [comment] 2019-07-12 08:09
unable to reproduce the given error.
can you provide some detailed steps to repro this.

**Comment by nduchak** [comment] 2019-07-12 15:41
Can we close this issue and related PR?

**Comment by nikita-fuchs** [comment] 2019-07-12 19:22
Yes, please close for now, this is all part of another issue.

Am Fr., 12. Juli 2019, 17:41 hat naz_dou <notifications@github.com>
geschrieben:

**Closed** 2019-07-12 20:49 UTC
