### ISSUE TITLE
Cannot call contract when rpcClient could not be connected

### ISSUE THREAD

**Issue by ifaouibadi** [aeternity/aepp-sdk-js#1452] opened 2022-03-31 09:33 UTC
**Describe the bug**
Safari and IOS  rpcClient not working.

In this case we use deep linking to connect to the user wallet, and when we try to call a contract it uses the dry-run address when it's supposed to use the `onAccount` provided

**To Reproduce**

```javascript
const node = await Node({
  url: 'https://testnet.aeternity.io' 
})

const client = await Universal({
  nodes: [
    { name: 'testnet', instance: node }
  ],
  compilerUrl: 'https://compiler.aepps.com',
})

const CONTRACT_SOURCE = ... // source code of the contract
const contractInstance = await client.getContractInstance({ source: CONTRACT_SOURCE })


const tx = await contractInstance.methods.call(**args, callStatic: false, onAccount = 'ak_....') // <= this will throw Error('You are not connected to Wallet')

```

**Expected behavior**
```javascript
const tx = await contractInstance.methods.call(**args, callStatic: false, onAccount = 'ak_....')
```
^^should use `onAccount` without checking the rcpClient

**Please tell us about your environment:**
  - Node Version: v16.13.1
  - SDK Version: v10.0.0

**Suggested fix** 
return onAccount when provided without checking for the rpcClient

src/utils/aepp-wallet-communication/rpc/aepp-rpc.js

````javascript
async address() {
  let {
    onAccount
  } = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

  if (onAccount) return onAccount // fix

  if (!this.rpcClient || !this.rpcClient.isConnected()) throw new Error('You are not connected to Wallet');
  const current = this.rpcClient.currentAccount;
  if (!current) throw new Error('You are not subscribed for an account.');
  return current;
},

**Comment by marc0olo** [comment] 2022-03-31 19:06
@ifaouibadi can you verify if this is still a problem with `v11.0.0` ?

**Comment by ifaouibadi** [comment] 2022-03-31 19:10
Yes this issue exists in v11 too

**Comment by subhod-i** [comment] 2022-04-01 14:46
@ifaouibadi Where exactly the `OnAccount` account exist?
In Wallet or a Memory account?

**Comment by subhod-i** [comment] 2022-04-01 14:48
```javascript
const tx = await contractInstance.methods.call(**args, callStatic: false, onAccount = 'ak_....') 
// where exactly private keys of this account stored? 
```

**Comment by subhod-i** [comment] 2022-04-01 14:52
I guess this is duplicate of https://github.com/aeternity/aepp-sdk-js/issues/1390

**Comment by davidyuk** [comment] 2022-04-14 15:12
`Universal` doesn't have any reference to RpcClient, did you mean `RpcAepp`?

In #1464 I implemented the `onAccount` option in `RpcAepp` that accepts something that implements `AccountBase` interface or a `KeyPair`. If you don't have access to a private key, you can create own implementation of `AccountBase` that returns the needed address and throws an exception while trying to sign something. Does it fits for you?

If not, would be nice to have a complete reproduction as a web page that can be runned in Safary/iOS to work with it.

**Comment by davidyuk** [comment] 2022-08-02 13:32
Closed for inactivity

**Closed by davidyuk** 2022-08-02 13:32 UTC
Labels: bug
